# docker-compose.yml
services:
  ncity-admin-app:
    build: .
    container_name: ncity-admin
    restart: always
    ports:
      - "127.0.0.1:3001:3000" # Внутри контейнера Next.js слушает 3000, но для Nginx мы отдаем его локально на 3001
    environment:
      DATABASE_URL: "postgresql://adm:Parol!@dbpg:5432/ncity_db"
      NODE_ENV: "production"
    networks:
      - ncity-shared-network

networks:
  ncity-shared-network:
    external: true
